POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imhlbm5hIiwiaWQiOiI1ZWI1NDE4YTM2NDM1YjY5MmNkOTVmMDYiLCJpYXQiOjE1ODg5MzcxMzV9.BnUaMXJoBcN7JQCYn2uTzTx8Ctooo-ovOi1bexyyld4

{
    "title": "superb",
    "author": "super",
    "url": "super",
    "likes": 1234,
    "userId": "5eb117443de49f55680f538b"
}